[package]
name = "krawler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
dotenvy = "0.15.6"
reqwest = { version = "0.11.13", features = ["json"] }
select = "0.5.0"
tokio = { version = "1.21.2", features = ["full"] }
